apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pvc
  labels:
    app: demo
    pvc: demo
spec:
  storageClassName: wcppolicy
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: filebrowser
  labels:
    app: filebrowser
spec:
  ports:
  - port: 80
    name: filebrowser
    targetPort: 8080
  selector:
    app: filebrowser
  type: LoadBalancer
